name: Deploy MVP to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Inject MAPBOX_TOKEN into index.html
        run: |
          sed "s/__MAPBOX_TOKEN__/${{ secrets.MAPBOX_TOKEN }}/g" mvp/index.html > mvp/index.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: mvp/

      - name: Deploy to Pages
        uses: actions/deploy-pages@v4

